### ISSUE TITLE
Missing currency handling in class heidelpayPHP\Resources\TransactionTypes\Cancellation

### ISSUE THREAD

**Issue by KristianH** [heidelpay/heidelpayPHP#125]
Since the Rest Api provides the information of the currency, I want to display this info into a shop system.
f.E.: https://api.heidelpay.com/v1/payments/s-pay-1/authorize/s-aut-1/cancels/s-cnl-1
[master::class: heidelpayPHP\Resources\TransactionTypes\Cancellation](https://github.com/heidelpay/heidelpayPHP/blob/master/src/Resources/TransactionTypes/Cancellation.php)

**Comment by sixer1182** [comment]
Hi @KristianH,
I will add this in the upcomming release (see PR #126 ).

Have a nice one
Simon

**Comment by KristianH** [comment]
Thank you Simon
