### ISSUE TITLE
Error in documentation, missing method $paypage->getToken()

### ISSUE THREAD

**Issue by dmagician** [heidelpay/heidelpayPHP#166]
I was trying to implement "Embedded Payment Page" and I've got an error "Attempted to call an undefined method named "getToken" of class..."

![image](https://user-images.githubusercontent.com/560489/78811041-8b428000-79c9-11ea-86d2-5bb5959f1396.png)

Then if found out that in example sources, that's it's not used there. So what now? Fix the docs, implement the method, or is it just something that I'm missing? (I'm just starting with heidelpay)

**Comment by sixer1182** [comment]
Hi @dmagician 
I am terribly sorry.
This is an error within our documentation.
Please use the id of the paypage instead of the token:
$paypage->getId()

We will update the documentation as soon as possible.
Have a nice day.
Simon

**Comment by sixer1182** [comment]
hi @dmagician 
the documentation has been updated.

Thanks again for the hint.
Simon

**Comment by dmagician** [comment]
I have figured out when checking code examples, thank you for your effort guys! Excellent docs and SDK.

**Comment by sixer1182** [comment]
You are very welcome @dmagician 
it is great to hear it is all worth it.
