### ISSUE TITLE
Encountered json_encode bug in AbstractHeidelpayResource.php

### ISSUE THREAD

**Issue by Obscuras** [heidelpay/heidelpayPHP#204]
We just implemented this API and encountered a PHP bug/change during the request of the resource Id / charge.

In our test we requested a charge of an amount of 190.82€, and the json_encode method in the AbstractHeidelpayResource.php on line 329 changed the amount to this value in the encoded json
190.81999999999999317878973670303821563720703125

![json_encode](https://user-images.githubusercontent.com/17937540/91966344-fe021e00-ed11-11ea-99b4-90600e797ebf.png)

Of course this value is rejected by your API (max 4 digits allowed).

So why json_encode is doing this? -> https://bugs.php.net/bug.php?id=72567

Our solution is now:
`public function jsonSerialize()`
`    {`
`        if (version_compare(phpversion(), '7.1', '>=')) {`
`            ini_set( 'serialize_precision', -1 );`
`        }`
`        return json_encode($this->expose(), JSON_UNESCAPED_SLASHES | JSON_PRESERVE_ZERO_FRACTION);`
`    }`

I hope this will help.

best regards
S.Schümann (Batronix GmbH & Co. KG, Germany)

**Comment by sixer1182** [comment]
Hello @Obscuras 
thanks for your message.
Actually this is not a bug.
The solution you propose here is one of the prerequisites to use this SDK.
See the documentation here: https://docs.heidelpay.com/docs/installation#php-configuration
Please set the value in your php.ini to avoid using the workaround which is not update save.

Best regards,
Simon
